<?php

/**
 * PluginPunchRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPunchRecordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginPunchRecordTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPunchRecord');
    }
}