<?php

/**
 * PunchRecordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PunchRecordTable extends PluginPunchRecordTable
{
    /**
     * Returns an instance of this class.
     *
     * @return PunchRecordTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PunchRecord');
    }
}