<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2022/03/20 07:00:20

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=127.0.0.1;port=3306;dbname=koinobor_webe578;charset=utf8mb4',
  'username' => 'root',
  'password' => 'entrarleya',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
